export default {
  login: 'keremcanb',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars.githubusercontent.com/u/61220117?s=400&u=6e4dcee5cc67120865160e96f0c003fc1146ea1c&v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/keremcanb',
  html_url: 'https://github.com/keremcanb',
  followers_url: 'https://api.github.com/users/keremcanb/followers',
  following_url: 'https://api.github.com/users/keremcanb/following{/other_user}',
  gists_url: 'https://api.github.com/users/keremcanb/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/keremcanb/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/keremcanb/subscriptions',
  organizations_url: 'https://api.github.com/users/keremcanb/orgs',
  repos_url: 'https://api.github.com/users/keremcanb/repos',
  events_url: 'https://api.github.com/users/keremcanb/events{/privacy}',
  received_events_url: 'https://api.github.com/users/keremcanb/received_events',
  type: 'User',
  site_admin: false,
  name: 'Keremcan Buyuktaskin',
  company: 'Freelancer',
  blog: 'www.keremcanb.com',
  location: 'Bodrum',
  email: null,
  hireable: null,
  bio: 'Full Stack Developer',
  twitter_username: 'keremcanb',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z'
};
